version: '3'

volumes:
  pg_kdata:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_kdata:/var/lib/postgresql/data

  backend:
    build: fyuriko/k_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    build: fyuriko/k_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: fyuriko/k_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media/
    depends_on:
      - backend
